### ISSUE TITLE
Missing Key

### ISSUE THREAD

**Issue by wrightzombie** [mysll/unraid_test#2]
Hi

I followed the instructions onto add the extra info into the go file and add the BTRS.key to config file.

i remade the usb bootable and booted it and it still says missing key file and as it boots it says 

error id.so object '/boot/config/BTRS.key' from ld_preload cannot be preloaded (invalid elf header): ignored.

**Comment by mysll** [comment]
build in slackware
or download https://github.com/mysll/unraid_test/tree/0b54912b7a2625865527e6752cf8b0ee3b700fd7

**Comment by whoshoe** [comment]
Is this method still valid in 6.11? Tried 6.11 rc4, not working.

**Comment by wrightzombie** [comment]
> Is this method still valid in 6.11? Tried 6.11 rc4, not working.

Pass bud on version 6.11. Works perfectly fine on version 6.10.3

**Comment by whoshoe** [comment]
> > Is this method still valid in 6.11? Tried 6.11 rc4, not working.
> 
> Pass bud on version 6.11. Works perfectly fine on version 6.10.3

Invalid arument. Might need some changes

**Comment by wrightzombie** [comment]
> > > Is this method still valid in 6.11? Tried 6.11 rc4, not working.
> > 
> > Pass bud on version 6.11. Works perfectly fine on version 6.10.3
> 
> Invalid arument. Might need some changes


Not all the info goes in the btrs.key file it now goes in 2 files

**Comment by whoshoe** [comment]
> > > > Is this method still valid in 6.11? Tried 6.11 rc4, not working.
> > > 
> > > 
> > > Pass bud on version 6.11. Works perfectly fine on version 6.10.3
> > 
> > 
> > Invalid arument. Might need some changes
> 
> Not all the info goes in the btrs.key file it now goes in 2 files

What's the other file?

**Comment by wrightzombie** [comment]
> > > > > Is this method still valid in 6.11? Tried 6.11 rc4, not working.
> > > > 
> > > > 
> > > > Pass bud on version 6.11. Works perfectly fine on version 6.10.3
> > > 
> > > 
> > > Invalid arument. Might need some changes
> > 
> > Not all the info goes in the btrs.key file it now goes in 2 files
> 
> What's the other file?

boot/config/btrs.key

Btrs.key is the licence on its own


This is for the go file

Location is /boot/config/go

export UNRAID_GUID=usb flash GUID
export UNRAID_NAME=your name
export UNRAID_DATE=unix timestamp
export UNRAID_VERSION=Pro
LD_PRELOAD=/boot/config/BTRS.key /usr/local/sbin/emhttp &


Guid is your usb key this needs to be in the btrs file and go file

Name can be anything

Unix timestamp can be done on Google.

And you can leave the others.

Once done and on usb re run make bootable

**Comment by whoshoe** [comment]
> > > > > > Is this method still valid in 6.11? Tried 6.11 rc4, not working.
> > > > > 
> > > > > 
> > > > > Pass bud on version 6.11. Works perfectly fine on version 6.10.3
> > > > 
> > > > 
> > > > Invalid arument. Might need some changes
> > > 
> > > 
> > > Not all the info goes in the btrs.key file it now goes in 2 files
> > 
> > 
> > What's the other file?
> 
> boot/config/btrs.key
> 
> Btrs.key is the licence on its own
> 
> This is for the go file
> 
> Location is /boot/config/go
> 
> export UNRAID_GUID=usb flash GUID export UNRAID_NAME=your name export UNRAID_DATE=unix timestamp export UNRAID_VERSION=Pro LD_PRELOAD=/boot/config/BTRS.key /usr/local/sbin/emhttp &
> 
> Guid is your usb key this needs to be in the btrs file and go file
> 
> Name can be anything
> 
> Unix timestamp can be done on Google.
> 
> And you can leave the others.
> 
> Once done and on usb re run make bootable

Well I get that. I had it working back in June and I have no issue on 6.10.x. I was talking about getting it to work on 6.11 rc4.  With this approach I am having an "invalid arguement" error on line 22.
