### ISSUE TITLE
大佬6.11 rc3这个方法不能激活了

### ISSUE THREAD

**Issue by jwkinko** [mysll/unraid_test#3]
6.11 rc3 已经失效了。

**Comment by jwkinko** [comment]
通过了

**Comment by sishen127** [comment]
怎么弄，6.11 rc4 这个方法失效了

**Comment by darkangelx78** [comment]
6.11 released and this method not working, do you how to fix maybe ?

**Comment by yhboss** [comment]
> 6.11 released and this method not working, do you how to fix maybe ?

Hi, I saw you have succeeded in fixing 6.11 following @springhack's instructions. But he has deleted his shared code. Could you please share how to do it?
